This PR fix the issue-1239
UXPin/adele pull request #151
Opened 2022-12-08 08:33 UTC by mrch4n

close https://github.com/UXPin/uxpin-issues/issues/1239

The `npm run template-build` cmd is broken.
Root cause is npm removed `npm_config_*` env var since V6 (https://github.com/npm/rfcs/blob/main/implemented/0021-reduce-lifecycle-script-environment.md)

2022-12-08 09:01 UTC, michaelrambeau requested changes
Thank you Henry, it work but why creating a new `template-helper-helper` file instead of putting the arg parsing logic inside `template-builder`?

It's a bit weird to have a script file that calls another script file using `node` executable instead of simply calling JS functions... unless I miss something you know 😅

2022-12-08 09:09 UTC, mrch4n commented
Yes, I agree it is a bit weird 😅
But in our situation(we are calling two js scripts in one npm cmd), I can only found this [solution](https://stackoverflow.com/questions/51388921/pass-command-line-args-to-npm-scripts-in-package-json#:~:text=Solution%202%20%2D%20Cross%2Dplatform%3A) which works on both *nix and windows machine ...

2022-12-08 12:02 UTC, michaelrambeau commented
OK so now I understand the context: we have 2 actions `template-builder` and `data-builder` that we want to combine in one single script, `data-builder` having to run after `template-builder`.

The problem is that we need to pass one argument from the command line but this argument is lost when we combine scripts doing `node action1 && node action2`.

The current solution is... hacky! (I have never seen that `JSON.parse(process.env.npm_config_argv, null, 2).remain[0];`).

Since we want to run `data-builder` after the `template-builder`, why not using NPM `post` scripts?

```json
{
    "template-build": "node tools/template-builder",
    "posttemplate-build": "npm run data-build",
}
```

A more robust solution would be to split commandds and actions, having a file that `exports` a `buildData()` function we could call from several places, for example, but the `post` script solution may be enough for now?

2022-12-09 02:30 UTC, mrch4n commented
Hey Michael!
Thanks for your comment. Yes this is the perfect solution, I don't know we can use `pre` and `post` keywords 😄 I learnt something new, thanks you!

I updated my commit, please check 🙂

2022-12-09 03:19 UTC, michaelrambeau approved these changes
👍 Perfect, thank you for having removed the weird code 😄

2022-12-12 01:25 UTC, merged